export const dummyData = [
  {
    interArrival: 0,
    serviceTime: 2,
    arrival: 0,
    startTime: 0,
    endTime: 2,
    waitTime: 0,
    turnaroundTime: 2,
    server: 1,
  },
  {
    interArrival: 10,
    serviceTime: 3,
    arrival: 10,
    startTime: 10,
    endTime: 13,
    waitTime: 0,
    turnaroundTime: 3,
    server: 2,
  },
  {
    interArrival: 13,
    serviceTime: 2,
    arrival: 23,
    startTime: 23,
    endTime: 25,
    waitTime: 0,
    turnaroundTime: 2,
    server: 1,
  },
  {
    interArrival: 1,
    serviceTime: 4,
    arrival: 24,
    startTime: 24,
    endTime: 28,
    waitTime: 0,
    turnaroundTime: 4,
    server: 2,
  },
  {
    interArrival: 13,
    serviceTime: 3,
    arrival: 37,
    startTime: 37,
    endTime: 40,
    waitTime: 0,
    turnaroundTime: 3,
    server: 1,
  },
  {
    interArrival: 9,
    serviceTime: 4,
    arrival: 46,
    startTime: 46,
    endTime: 50,
    waitTime: 0,
    turnaroundTime: 4,
    server: 1,
  },
  {
    interArrival: 1,
    serviceTime: 4,
    arrival: 47,
    startTime: 47,
    endTime: 51,
    waitTime: 0,
    turnaroundTime: 4,
    server: 2,
  },
  {
    interArrival: 6,
    serviceTime: 2,
    arrival: 53,
    startTime: 53,
    endTime: 55,
    waitTime: 0,
    turnaroundTime: 2,
    server: 1,
  },
  {
    interArrival: 16,
    serviceTime: 5,
    arrival: 69,
    startTime: 69,
    endTime: 74,
    waitTime: 0,
    turnaroundTime: 5,
    server: 2,
  },
  {
    interArrival: 6,
    serviceTime: 1,
    arrival: 75,
    startTime: 75,
    endTime: 76,
    waitTime: 0,
    turnaroundTime: 1,
    server: 1,
  },
  {
    interArrival: 7,
    serviceTime: 1,
    arrival: 82,
    startTime: 82,
    endTime: 83,
    waitTime: 0,
    turnaroundTime: 1,
    server: 1,
  },
  {
    interArrival: 16,
    serviceTime: 1,
    arrival: 98,
    startTime: 98,
    endTime: 99,
    waitTime: 0,
    turnaroundTime: 1,
    server: 1,
  },
  {
    interArrival: 9,
    serviceTime: 2,
    arrival: 107,
    startTime: 107,
    endTime: 109,
    waitTime: 0,
    turnaroundTime: 2,
    server: 1,
  },
  {
    interArrival: 15,
    serviceTime: 13,
    arrival: 122,
    startTime: 122,
    endTime: 135,
    waitTime: 0,
    turnaroundTime: 13,
    server: 2,
  },
  {
    interArrival: 11,
    serviceTime: 4,
    arrival: 133,
    startTime: 133,
    endTime: 137,
    waitTime: 0,
    turnaroundTime: 4,
    server: 1,
  },
  {
    interArrival: 6,
    serviceTime: 2,
    arrival: 139,
    startTime: 139,
    endTime: 141,
    waitTime: 0,
    turnaroundTime: 2,
    server: 1,
  },
  {
    interArrival: 11,
    serviceTime: 1,
    arrival: 150,
    startTime: 150,
    endTime: 151,
    waitTime: 0,
    turnaroundTime: 1,
    server: 1,
  },
];
